server:
  port: 8080
spring:
  application:
    name: electronicsstore
  datasource:
    url: jdbc:mysql://localhost:3306/electronicsstore
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
logging:
  pattern:
    file: "%d %-5level [%thread] %mdc %logger : %msg%n"
  file: ./log/application.log
